/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as GouvernanceRouteImport } from './routes/gouvernance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const GouvernanceRoute = GouvernanceRouteImport.update({
  id: '/gouvernance',
  path: '/gouvernance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mission'
    | '/reseau'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mission'
    | '/reseau'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mission'
    | '/reseau'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  ContactRoute: typeof ContactRoute
  GouvernanceRoute: typeof GouvernanceRoute
  InvestisseursRoute: typeof InvestisseursRoute
  MissionRoute: typeof MissionRoute
  ReseauRoute: typeof ReseauRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gouvernance': {
      id: '/gouvernance'
      path: '/gouvernance'
      fullPath: '/gouvernance'
      preLoaderRoute: typeof GouvernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  ContactRoute: ContactRoute,
  GouvernanceRoute: GouvernanceRoute,
  InvestisseursRoute: InvestisseursRoute,
  MissionRoute: MissionRoute,
  ReseauRoute: ReseauRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
