/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as GouvernanceRouteImport } from './routes/gouvernance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const GouvernanceRoute = GouvernanceRouteImport.update({
  id: '/gouvernance',
  path: '/gouvernance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/gouvernance': typeof GouvernanceRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mission': typeof MissionRoute
  '/reseau': typeof ReseauRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibilite'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mentions-legales'
    | '/mission'
    | '/reseau'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilite'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mentions-legales'
    | '/mission'
    | '/reseau'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/accessibilite'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/gouvernance'
    | '/investisseurs'
    | '/mentions-legales'
    | '/mission'
    | '/reseau'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibiliteRoute: typeof AccessibiliteRoute
  ActualitesRoute: typeof ActualitesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  GouvernanceRoute: typeof GouvernanceRoute
  InvestisseursRoute: typeof InvestisseursRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MissionRoute: typeof MissionRoute
  ReseauRoute: typeof ReseauRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gouvernance': {
      id: '/gouvernance'
      path: '/gouvernance'
      fullPath: '/gouvernance'
      preLoaderRoute: typeof GouvernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibiliteRoute: AccessibiliteRoute,
  ActualitesRoute: ActualitesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  GouvernanceRoute: GouvernanceRoute,
  InvestisseursRoute: InvestisseursRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MissionRoute: MissionRoute,
  ReseauRoute: ReseauRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
